commerce03/src/main/java/com/supercoding/commerce03/repository/user/entity/User.java
commerce03/src/main/java/com/supercoding/commerce03/repository/user/entity/UserDetail.java

#본문: 코드 의도 설명 가능한 자세하게
Feat : User 엔티티 추가 했습니다
예시
아이디랑 비밀번호를 입력받아서 값을 검증하고 DB에 회원 정보를 저장합니다.
응답값은 비밀번호를 제외한 입력값을 반환합니다.

#제목: 구현한 기능 User와 UserDetail 엔티티를 추가 했습니다

---

commerce03/src/main/java/com/supercoding/commerce03/repository/user/entity/User.java
commerce03/src/main/java/com/supercoding/commerce03/repository/user/entity/UserDetail.java

#본문: 코드 의도 설명 가능한 자세하게
Feat : User, UserDetail 엔티티 부분 수정했습니다(Not Null)
예시
아이디랑 비밀번호를 입력받아서 값을 검증하고 DB에 회원 정보를 저장합니다.
응답값은 비밀번호를 제외한 입력값을 반환합니다.

#제목: 구현한 기능

---

commerce03/src/main/java/com/supercoding/commerce03/repository/order/entity/Order.java
commerce03/src/main/java/com/supercoding/commerce03/repository/order/entity/OrderDetail.java

테이블 칼럼 변경에 따른 엔티티 수정 + 관계 매핑 수정

Refactor/order : 엔티티 수정

---

commerce03/src/main/java/com/supercoding/commerce03/repository/order/entity/Order.java
commerce03/src/main/java/com/supercoding/commerce03/repository/order/entity/OrderDetail.java

Refactor/order : 테이블 변경에 따른 엔티티 수정 + 관계  매핑 변경 

---

commerce03/src/main/java/com/supercoding/commerce03/repository/order/entity/Order.java

Refactor : 테이블 변경에 따른 엔티티 필드 추가

---

commerce03/src/main/java/com/supercoding/commerce03/repository/order/entity/OrderDetail.java

UserDetails 엔티티 id 필드 타입 Integer -> Long으로 변경

Refactor : 엔티티 변경

---

commerce03/src/main/java/com/supercoding/commerce03/service/cart/exception/CartErrorCode.java
commerce03/src/main/java/com/supercoding/commerce03/web/advice/LoggingAspect.java

Refactor : LoggingAspect 파일 이동

---

commerce03/build.gradle
commerce03/src/main/java/com/supercoding/commerce03/config/security/PasswordEncoderConfig.java
commerce03/src/main/java/com/supercoding/commerce03/config/security/SecurityConfig.java
commerce03/src/main/java/com/supercoding/commerce03/service/security/Auth.java
commerce03/src/main/java/com/supercoding/commerce03/service/security/AuthHolder.java
commerce03/src/main/java/com/supercoding/commerce03/service/security/AuthInterceptor.java
commerce03/src/main/java/com/supercoding/commerce03/service/security/JwtTokenProvider.java
commerce03/src/main/java/com/supercoding/commerce03/service/security/TokenFilter.java

본문: 토큰 생성과 비밀번호 암호화 스프링 시큐리티에 대한 기본설정을 했습니다 확인 부탁드립니다.실행시 문제는 없었으나 코드상 문제가 있다고 생각이 되시면 말씀 한번씩 부탁드립니다.
Feat : JWT 스프링 시큐리티 기본 설정

제목: JWT와 시큐리티 기본 설정

---

commerce03/src/main/java/com/supercoding/commerce03/service/cart/CartService.java
commerce03/src/main/java/com/supercoding/commerce03/web/controller/cart/CartController.java
commerce03/src/main/java/com/supercoding/commerce03/web/dto/cart/RemoveCart.java

Refactor : 장바구니 삭제 수정

---

commerce03/build.gradle
commerce03/src/main/java/com/supercoding/commerce03/repository/order/OrderDetailRepository.java
commerce03/src/main/java/com/supercoding/commerce03/repository/order/entity/Order.java
commerce03/src/main/java/com/supercoding/commerce03/repository/order/entity/ProductAndOrderAmount.java
commerce03/src/main/java/com/supercoding/commerce03/service/order/OrderService.java
commerce03/src/main/java/com/supercoding/commerce03/service/order/exception/OrderErrorCode.java
commerce03/src/main/java/com/supercoding/commerce03/service/order/exception/OrderErrorResponse.java
commerce03/src/main/java/com/supercoding/commerce03/service/order/exception/OrderException.java
commerce03/src/main/java/com/supercoding/commerce03/service/order/mapper/OrderMapper.java
commerce03/src/main/java/com/supercoding/commerce03/web/controller/order/OrderController.java
commerce03/src/main/java/com/supercoding/commerce03/web/dto/order/OrderDto.java

현재 결제되어 포인트 차감되는 부분 빼고 정상 기능합니다.

Feature/order register 주문 하기 API 

---

commerce03/src/main/java/com/supercoding/commerce03/repository/cart/CartRepository.java
commerce03/src/main/java/com/supercoding/commerce03/service/cart/CartService.java
commerce03/src/main/java/com/supercoding/commerce03/web/controller/cart/CartController.java

Refactor : 내 장바구니 가져오기 수정

---

commerce03/src/main/java/com/supercoding/commerce03/service/security/JwtTokenProvider.java
commerce03/src/main/java/com/supercoding/commerce03/service/security/TokenFilter.java
commerce03/src/main/java/com/supercoding/commerce03/service/user/UserDetailService.java

JwtTockenProvider, TokenFilter 파일 수정본입니다

# Refactor : 시큐리티 코드 수정본 올리겠습니다

---

commerce03/src/main/java/com/supercoding/commerce03/repository/account/AccountRepository.java
commerce03/src/main/java/com/supercoding/commerce03/repository/account/entity/Account.java
commerce03/src/main/java/com/supercoding/commerce03/repository/account/entity/AccountByType.java
commerce03/src/main/java/com/supercoding/commerce03/repository/payment/PaymentRepository.java
commerce03/src/main/java/com/supercoding/commerce03/repository/payment/entity/Payment.java
commerce03/src/main/java/com/supercoding/commerce03/service/account/AccountService.java
commerce03/src/main/java/com/supercoding/commerce03/service/payment/PaymentService.java
commerce03/src/main/java/com/supercoding/commerce03/web/controller/account/AccountController.java
commerce03/src/main/java/com/supercoding/commerce03/web/controller/payment/PaymentController.java
commerce03/src/main/java/com/supercoding/commerce03/web/dto/account/CreateAccount.java

Feat payment 구현

---

commerce03/src/main/java/com/supercoding/commerce03/service/order/OrderService.java
commerce03/src/main/java/com/supercoding/commerce03/service/payment/PaymentService.java
commerce03/src/main/java/com/supercoding/commerce03/web/controller/order/OrderController.java

Refactor/order 결제 로직 추가  

---

commerce03/src/main/java/com/supercoding/commerce03/service/payment/PaymentService.java
commerce03/src/main/java/com/supercoding/commerce03/web/advice/GlobalExceptionHandler.java
commerce03/src/main/java/com/supercoding/commerce03/web/controller/payment/PaymentController.java

Feat 예외처리 코드 import

---

commerce03/src/main/java/com/supercoding/commerce03/service/user/UserService.java
commerce03/src/main/java/com/supercoding/commerce03/service/user/exception/UserErrorCode.java
commerce03/src/main/java/com/supercoding/commerce03/web/dto/user/SignUp.java
commerce03/src/main/java/com/supercoding/commerce03/web/dto/user/UpdateProfile.java

본문: 회원가입과 회원정보 수정시 체크용 비밀번호를 받고 있었는데 이러한 부분은 클라이언트 측에서 가능하다고 해서 코드 변경했습니다.
Refactor : 회원가입/수정시 checkPassword를 받아오는 부분을 삭제했습니다

제목: 회원가입/수정시 체크 비밀번호 삭제

---

commerce03/src/main/java/com/supercoding/commerce03/web/controller/cart/CartController.java

Refactor : CartController 수정

---

commerce03/src/main/java/com/supercoding/commerce03/web/dto/cart/GetCart.java

Refactor : GetCart Dto 수정

---

commerce03/src/main/java/com/supercoding/commerce03/service/order/OrderService.java

주문 상세를 저장하고, 불러오는 과정을 두개로 나누어 두었는데, 하나로 합쳐 구현 가능하여 하나로 변경

Refactor : 주문하기 로직에서 불필요한 로직 제거

---

commerce03/build.gradle
commerce03/src/main/java/com/supercoding/commerce03/web/dto/order/OrderDto.java
commerce03/src/test/java/com/supercoding/commerce03/service/order/OrderServiceOrderRegisterTest.java

Test/order : orderRegister 테스트 코드 추가 

---

commerce03/src/test/java/com/supercoding/commerce03/service/order/OrderServiceSpinLockTest.java

Test : 동시성 문제 해결을 위한 인메모리 스핀락 테스트
